---
name: docker-build-and-push

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Super-Linter
        uses: github/super-linter@v5
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: "main"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:  
          config-file-path: .super-linter.yaml

  docker-build-and-push:
    runs-on: ubuntu-latest
    needs: run-lint
    env:
      IMAGE_NAME: mladenovskistefan/dotnet-todo
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
    
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker image with Semantic Versioning
        run: |
          set -e
          IMAGE_VERSION="${GITHUB_REF_NAME}"
          docker build -t "$IMAGE_NAME:${IMAGE_VERSION}" .

      - name: Push Docker image
        run: |
          set -e
          IMAGE_VERSION="${GITHUB_REF_NAME}"
          docker push "$IMAGE_NAME:${IMAGE_VERSION}"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com

      - name: Tag Docker image for ECR
        run: |
          IMAGE_VERSION="${GITHUB_REF_NAME}"
          docker tag "$IMAGE_NAME:${IMAGE_VERSION}" "${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/dotnet-todo-repo:${IMAGE_VERSION}"

      - name: Push Docker image to Amazon ECR
        run: |
          IMAGE_VERSION="${GITHUB_REF_NAME}"
          docker push "${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/dotnet-todo-repo:${IMAGE_VERSION}"
