name: docker-build-and-push

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Super-Linter
        uses: github/super-linter@v5
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: "main"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker-build-and-push:
    runs-on: ubuntu-latest
    needs: run-lint
    env:
      IMAGE_NAME: mladenovskistefan/dotnet-todo
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image with Semantic Versioning
        run: |
          set -e
          IMAGE_VERSION=${GITHUB_REF_NAME}
          docker build -t $IMAGE_NAME:${IMAGE_VERSION} .

      - name: Push Docker image
        run: |
          set -e
          IMAGE_VERSION=${GITHUB_REF_NAME}
          docker push $IMAGE_NAME:${IMAGE_VERSION}
