---
name: helm-deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Minikube
        uses: manusa/actions-setup-minikube@v2.12.0
        with:
          minikube version: 'v1.34.0'
          kubernetes version: 'v1.31.1'
          driver: docker

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Create Kubernetes namespace
        run: |
          kubectl create namespace dotnet-todo-namespace || echo "Namespace 'dotnet-todo-namespace' already exists"
      
      - name: Deploy dotnet-app to Minikube
        run: |
          helm install dotnet-app ./helm --namespace dotnet-todo-namespace

      - name: Sleep for 120 seconds to allow deployment to settle
        run: |
          sleep 120

      - name: Check Deployment Status
        run: |
          kubectl get deployment -n dotnet-todo-namespace
          
      - name: Check Service Status
        run: |
          kubectl get service -n dotnet-todo-namespace
          
      - name: Check Pods Status
        run: |
          kubectl get pods -n dotnet-todo-namespace

      - name: Port-forward service to localhost
        run: |
          kubectl port-forward service/dotnet-app-service 80:80 -n dotnet-todo-namespace

      - name: Wait for port-forwarding to settle
        run: |
          sleep 10

      - name: Post sample todo items
        run: |
          curl -X POST http://localhost:80/todoitems -H "Content-Type: application/json" -d '{"id": 1, "name": "walk", "isComplete": false}'
          curl -X POST http://localhost:80/todoitems -H "Content-Type: application/json" -d '{"id": 2, "name": "study", "isComplete": true}'
          curl -X POST http://localhost:80/todoitems -H "Content-Type: application/json" -d '{"id": 3, "name": "work on task", "isComplete": true}'

      - name: Get all todo items
        run: |
          curl http://localhost:80/todoitems

      - name: Get todo item with id 1
        run: |
          curl http://localhost:80/todoitems/1

      - name: Get todo item with id 2
        run: |
          curl http://localhost:80/todoitems/2

      - name: Get todo item with id 3
        run: |
          curl http://localhost:80/todoitems/
